In [1]:
# import library for selenium
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# for Exception-Handling 
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# import library for BeautifulSoup
import bs4
from bs4 import BeautifulSoup
import requests

# for ignore warnings 
import warnings
warnings.filterwarnings('ignore')

# for DataFrame
import pandas as pd

Q-1-->Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:     
    A)Rank
    B) Name
    C) Artist
    D) Upload date
    E) Views

In [2]:
url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
page=requests.get(url)
page

In [3]:
soup=BeautifulSoup(page.content)
# print(soup.text)

In [4]:
rank=[]
name=[]
artist=[]
date=[]
views=[]

In [5]:
# for rank
ra=soup.find_all('td',align="center")
for i in ra:
    rank.append(i.text)
    rank=rank[0:30]
    
# for views
date=soup.find_all('td',align="center")
for i in date:
    views.append(i.text)
    views=views[0:30]
    
# for date
da=soup.find_all('td',align="right")
for i in da:
    date.append(i.text)
    date=date[0:30]

In [6]:
print(len(rank),len(views),len(date))

30 30 30

In [7]:
# for dataframe
df=pd.DataFrame({'Rank':rank,'Views in billions':views,'Publication_Date':date})
df.head()

    Rank Views in billions Publication_Date
0     1.                1.             [1.]
1  13.65             13.65          [13.65]
2  [A]\n             [A]\n    [[[[A]]], \n]
3     2.                2.             [2.]
4   8.32              8.32           [8.32]

In [8]:
driver=webdriver.Chrome()
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [9]:
ra=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr[1]/td[2]/a')
for i in ra:
    
    rank.append(i.get_attribute('href'))
    rank=rank[0:30]

In [10]:
print(len(rank))

30

In [11]:
url=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr[2]/td[2]/a')
for i in url:
    print(i.get_attribute('href'))

https://en.wikipedia.org/wiki/Despacito#Music_video

Q-2--> Scrape the details team Indiaâ€™s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:

A) Series
B) Place
C) Date
D) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [12]:
driver=webdriver.Chrome()
driver.get('https://www.bcci.tv/')

# for fixtures
fix=driver.find_element(By.XPATH,'//*[@id="imw-international-men"]/a[2]').click()

series=[]
place=[]
date=[]
time=[]

# for series
start=0
end=5
for page in range(start,end):
    se=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[1]/div/div/h5')
    for i in se:
        series.append(i.text)
        
# for place
start=0
end=5
for page in range(start,end):
    pl=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[2]/div[1]/span[1]')
    for i in pl:
        place.append(i.text)
        
        
# for Date 
start=0
end=5
for page in range(start,end):
    da=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[1]/div/div/div[2]/div[1]')
    for i in da:
        date.append(i.text)
    
# for time
for page in range(start,end):
    ti=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[1]/div/div/div[2]/div[2]')
    for i in ti:
        time.append(i.text)

In [13]:
print(len(series),len(place),len(date),len(time))

0 0 0 0

In [14]:
# for Data Frame
import pandas as pd
df=pd.DataFrame({'Series Name':series,'Place':place,'Date':date,'Time':time})
df.head()

Empty DataFrame
Columns: [Series Name, Place, Date, Time]
Index: []

Q-3--> Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: 

A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)


Note: - From statisticstimes home page you have to reach to economy page through code.

In [15]:
driver=webdriver.Chrome()
driver.get('https://www.statisticstimes.com/economy/india-statistics.php')

eco=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()

In [16]:
# Blanck list
rank=[]
state=[]
gsdp=[]
gsdp_new=[]
share=[]
gdp=[]


# for rank 
ra=driver.find_elements(By.CLASS_NAME,'data1')
for i in ra:
    rank.append(i.text)
    rank=rank[0:33]
    
# for State name
name=driver.find_elements(By.CLASS_NAME,'name')
for i in name:
    state.append(i.text)
    state=state[0:33]
    
# for GSDP(18-19)
gs=driver.find_elements(By.CLASS_NAME,'sorting_1')
for i in gs:
    gsdp.append(i.text)
    gsdp=gsdp[0:33]
    
# for GSDP (19-20)
dp=driver.find_elements(By.CLASS_NAME,'data')
for i in dp:
    gsdp_new.append(i.text)
    gsdp_new=gsdp_new[0:33]
    
    
# for share (18-19)
sh=driver.find_elements(By.CLASS_NAME,'data')
for i in sh:
    share.append(i.text)
    share=share[0:33]
    
    
# for GDP 
gd=driver.find_elements(By.CLASS_NAME,'data')
for i in gd:
    gdp.append(i.text)
    gdp=gdp[0:33]

In [17]:
print(len(rank),len(state),len(gsdp),len(gsdp_new),len(share),len(gdp))

33 33 33 33 33 33

In [18]:
# for Data Frame
import pandas as pd
df=pd.DataFrame({'Rank_of_State':rank,'State':state,'GSDP(18-19)':gsdp,'GSDP(19-20)':gsdp_new,'Share':share,'GDP':gdp})
df.head()

  Rank_of_State          State GSDP(18-19) GSDP(19-20)      Share        GDP
0             1    Maharashtra   2,632,792           -          -          -
1             2     Tamil Nadu   1,630,208   2,632,792  2,632,792  2,632,792
2             3  Uttar Pradesh   1,584,764      13.94%     13.94%     13.94%
3             4        Gujarat   1,502,899     399.921    399.921    399.921
4             5      Karnataka   1,493,127           -          -          -

Q-4--> Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:

A) Repository title
B) Repository description
C) Contributors count
D) Language used 

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [20]:
driver=webdriver.Chrome()
driver.get('https://github.com/search?q=trading&type=repositories')

In [127]:
repository=[]
description=[]
count=[]
language=[]

# For Repository Title 
start=0
end=5
for page in range(start,end):
    rep=driver.find_elements(By.CLASS_NAME,'bBwPjs')
    for i in rep:
        repository.append(i.text)
        repository=repository[0:50]
    
# For Reopsitory Description
for page in range(start,end):
    des=driver.find_elements(By.CLASS_NAME,'kWPXhV')
    for i in des:
        description.append(i.text)
        description=description[0:50]
        
        
# for Contributors count
for page in range(start,end):
    co=driver.find_elements(By.CLASS_NAME,'gPDEWA')
    for i in co:
        count.append(i.text)
        count=count[0:50]
        

# for Language Use
for page in range(0,5):
    lan=driver.find_elements(By.CLASS_NAME,'gVaQzD') # Box-sc-g0xbh4-0 
    for i in lan:
        language.append(i.text)
        language=language[0:50]

In [128]:
print(len(repository),len(description),len(count),len(language))

50 50 50 50

In [130]:
df=pd.DataFrame({'Repository Name':repository,'Description':description,'Contributors count':count,'Language Used':count})
df

,Repository Name,Description,Contributors count,Language Used
0,Superalgos/Superalgos,"Free, open-source crypto trading bot, automate...",,
1,freqtrade/freqtrade,"Free, open source crypto trading bot",,
2,edeng23/binance-trade-bot,Automated cryptocurrency trading bot,96.8k,96.8k
3,quantopian/zipline,"Zipline, a Pythonic Algorithmic Trading Library",,
4,mementum/backtrader,Python Backtesting library for trading strategies,,
5,StockSharp/StockSharp,Algorithmic trading and quantitative trading o...,66k,66k
6,gbeced/pyalgotrade,Python Algorithmic Trading Library,,
7,stefan-jansen/machine-learning-for-trading,Code for Machine Learning for Algorithmic Trad...,,
8,robcarver17/pysystemtrade,Systematic Trading in python,52k,52k
9,chrisleekr/binance-trading-bot,Automated Binance trading bot - Trade multiple...,,
10,Superalgos/Superalgos,"Free, open-source crypto trading bot, automate...",,
11,freqtrade/freqtrade,"Free, open source crypto trading bot",2k,2k
12,edeng23/binance-trade-bot,Automated cryptocurrency trading bot,,
13,quantopian/zipline,"Zipline, a Pythonic Algorithmic Trading Library",,
14,mementum/backtrader,Python Backtesting library for trading strategies,7k,7k
15,StockSharp/StockSharp,Algorithmic trading and quantitative trading o...,,
16,gbeced/pyalgotrade,Python Algorithmic Trading Library,,
17,stefan-jansen/machine-learning-for-trading,Code for Machine Learning for Algorithmic Trad...,,
18,robcarver17/pysystemtrade,Systematic Trading in python,JavaScript,JavaScript
19,chrisleekr/binance-trading-bot,Automated Binance trading bot - Trade multiple...,3.6k,3.6k
20,Superalgos/Superalgos,"Free, open-source crypto trading bot, automate...",Updated 7 hours ago,Updated 7 hours ago
21,freqtrade/freqtrade,"Free, open source crypto trading bot",7 hours ago,7 hours ago
22,edeng23/binance-trade-bot,Automated cryptocurrency trading bot,Python,Python
23,quantopian/zipline,"Zipline, a Pythonic Algorithmic Trading Library",23.5k,23.5k
24,mementum/backtrader,Python Backtesting library for trading strategies,Updated 4 hours ago,Updated 4 hours ago
25,StockSharp/StockSharp,Algorithmic trading and quantitative trading o...,4 hours ago,4 hours ago
26,gbeced/pyalgotrade,Python Algorithmic Trading Library,Python,Python
27,stefan-jansen/machine-learning-for-trading,Code for Machine Learning for Algorithmic Trad...,7.4k,7.4k
28,robcarver17/pysystemtrade,Systematic Trading in python,Updated 25 days ago,Updated 25 days ago
29,chrisleekr/binance-trading-bot,Automated Binance trading bot - Trade multiple...,25 days ago,25 days ago
30,Superalgos/Superalgos,"Free, open-source crypto trading bot, automate...",Python,Python
31,freqtrade/freqtrade,"Free, open source crypto trading bot",16.6k,16.6k
32,edeng23/binance-trade-bot,Automated cryptocurrency trading bot,Updated on Jul 17,Updated on Jul 17
33,quantopian/zipline,"Zipline, a Pythonic Algorithmic Trading Library",on Jul 17,on Jul 17
34,mementum/backtrader,Python Backtesting library for trading strategies,Python,Python
35,StockSharp/StockSharp,Algorithmic trading and quantitative trading o...,12k,12k
36,gbeced/pyalgotrade,Python Algorithmic Trading Library,Updated 7 days ago,Updated 7 days ago
37,stefan-jansen/machine-learning-for-trading,Code for Machine Learning for Algorithmic Trad...,7 days ago,7 days ago
38,robcarver17/pysystemtrade,Systematic Trading in python,C#,C#
39,chrisleekr/binance-trading-bot,Automated Binance trading bot - Trade multiple...,6.2k,6.2k
40,Superalgos/Superalgos,"Free, open-source crypto trading bot, automate...",Updated 20 hours ago,Updated 20 hours ago
41,freqtrade/freqtrade,"Free, open source crypto trading bot",20 hours ago,20 hours ago
42,edeng23/binance-trade-bot,Automated cryptocurrency trading bot,Python,Python
43,quantopian/zipline,"Zipline, a Pythonic Algorithmic Trading Library",4.2k,4.2k
44,mementum/backtrader,Python Backtesting library for trading strategies,Updated 14 days ago,Updated 14 days ago
45,StockSharp/StockSharp,Algorithmic trading and quantitative trading o...,14 days ago,14 days ago
46,gbeced/pyalgotrade,Python Algorithmic Trading Library,Jupyter Notebook,Jupyter Notebook
47,stefan-jansen/machine-learning-for-trading,Code for Machine Learning for Algorithmic Trad...,10.8k,10.8k
48,robcarver17/pysystemtrade,Systematic Trading in python,Updated on Jun 21,Updated on Jun 21
49,chrisleekr/binance-trading-bot,Automated Binance trading bot - Trade multiple...,on Jun 21,on Jun 21

Q-- 5--> Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:

A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

 Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [132]:
driver=webdriver.Chrome()
driver.get('https:/www.billboard.com/')

In [134]:
# chart=driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a').click()
hot=driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span/a').click()

In [209]:
name=[]
artist=[]
week=[]
rank=[]
board=[]

# for Song name
na=driver.find_elements(By.XPATH,'//*[@id="title-of-a-story"]')
for i in na:
    name.append(i.text)
    name=name[0:100]
    
# for artist
ar=driver.find_elements(By.CLASS_NAME,'c-label')
for i in ar:    
    artist.append(i.text)
    artist=artist[0:100]
    
    
# for Last week rank 
last=driver.find_elements(By.CLASS_NAME,'a-font-primary-bold-l')
for i in last:
    week.append(i.text)
    week=week[0:100]
    

# For Peak rank
last=driver.find_elements(By.CLASS_NAME,'a-font-primary-m')
for i in last:
    rank.append(i.text)
    rank=rank[0:100]
    
# for Weeks on board
last=driver.find_elements(By.CLASS_NAME,'a-font-primary-bold-l')
for i in last:
    board.append(i.text)
    board=board[0:100]

In [208]:
print(len(name),len(artist),len(week),len(rank),len(board))

100 100 100 100

In [210]:
# for Data Frame
df=pd.DataFrame({'Song Name':name,'Artist Name':artist,'Last week rank':week,'peak rank':rank,'weeks on board':board})
df

,Song Name,Artist Name,Last week rank,peak rank,weeks on board
0,,1,Billboard Hot 100â„¢,,Billboard Hot 100â„¢
1,,4,Cruel Summer,-,Cruel Summer
2,,28,Billboard Hot 100â„¢,2,Billboard Hot 100â„¢
3,,1,1,1,1
4,,Taylor Swift,1,,1
...,...,...,...,...,...
95,,12,87,,87
96,,Chris Stapleton,88,,88
97,,29,89,13,89
98,Monaco,12,90,4,90
99,,17,91,22,91

Q--> 6--> Scrape the details of Highest selling novels.

A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [3]:
driver=webdriver.Chrome()
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [67]:
# for making list
book=[]
author=[]
sold=[]
publisher=[]
genre=[]

# for book name
name=driver.find_elements(By.CLASS_NAME,'left')
for i in name:
    book.append(i.text)
    book=book[0:100]
    
# for author name
aut=driver.find_elements(By.CLASS_NAME,'left')
for i in aut:
    author.append(i.text)
    author=author[0:100]
    
    
# for Volume Sold 
so=driver.find_elements(By.CLASS_NAME,'left')
for i in so:
    sold.append(i.text)
    sold=sold[0:100]
    
    
# for Publisher
pub=driver.find_elements(By.CLASS_NAME,'left')
for i in pub:
    publisher.append(i.text)
    publisher=publisher[0:100]
    
    
# for genere
ge=driver.find_elements(By.CLASS_NAME,'last')
for i in ge:
    genre.append(i.text)
    genre=genre[0:100]

In [70]:
print(len(book),len(author),len(sold),len(genre),len(publisher))

100 100 100 100 100

In [ ]:
# for Data Frame
import pandas as pd
df=pd.DataFrame({'Book Name':book,'Author Name':author,'Publisher':publisher,
                 'Volume sold':sold,'Genre':genre})
df

# sorry for this questions i tryed multiple time but i can't able to scrape the data from Table webpage

Q--7--> Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/ You have
to find the following details:
    
    
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [76]:
driver=webdriver.Chrome()
driver.get('https://www.imdb.com/list/ls095964455/')

In [135]:
name=[]
year=[]
genre=[]
run=[]
ratings=[]

# for name
na=driver.find_elements(By.CLASS_NAME,'lister-item-header')
for i in na:
    name.append(i.text)
    name=name[0:100]
    

# for years span
ye=driver.find_elements(By.CLASS_NAME,'lister-item-year')
for i in ye:
    year.append(i.text)
    year=year[0:100]
    
    
# for Genre 
ge=driver.find_elements(By.CLASS_NAME,'genre')
for i in ge:
    genre.append(i.text)
    genre=genre[0:100]
    
    
# fro Run Time
ru=driver.find_elements(By.CLASS_NAME,'runtime')
for i in ru:
    run.append(i.text)
    run=run[0:100]
    
    
# for Ratings 
rat=driver.find_elements(By.CLASS_NAME,'ipl-rating-widget')
for i in rat:
    ratings.append(i.text)
    ratings=ratings[0:100]

In [136]:
print(len(name),len(year),len(genre),len(run),len(ratings),len(votes))

100 100 100 100 100 100

In [137]:
# for Data Frame
df=pd.DataFrame({'Name':name,'Year Spane':year,'Genre':genre,'Run Time':run,'Ratings':ratings})
df

,Name,Year Spane,Genre,Run Time,Ratings
0,1. Game of Thrones (2011â€“2019),(2011â€“2019),"Action, Adventure, Drama","4,189 min",9.2\nRate
1,2. Stranger Things (2016â€“2025),(2016â€“2025),"Drama, Fantasy, Horror",51 min,8.7\nRate
2,3. The Walking Dead (2010â€“2022),(2010â€“2022),"Drama, Horror, Thriller",44 min,8.1\nRate
3,4. 13 Reasons Why (2017â€“2020),(2017â€“2020),"Drama, Mystery, Thriller",60 min,7.5\nRate
4,5. The 100 (2014â€“2020),(2014â€“2020),"Drama, Mystery, Sci-Fi",43 min,7.6\nRate
...,...,...,...,...,...
95,96. Reign (2013â€“2017),(2013â€“2017),Drama,42 min,7.5\nRate
96,97. A Series of Unfortunate Events (2017â€“2019),(2017â€“2019),"Adventure, Comedy, Drama",50 min,7.8\nRate
97,98. Criminal Minds (2005â€“ ),(2005â€“ ),"Crime, Drama, Mystery",42 min,8.1\nRate
98,99. Scream: The TV Series (2015â€“2019),(2015â€“2019),"Comedy, Crime, Drama",45 min,7\nRate
99,100. The Haunting of Hill House (2018),(2018),"Drama, Horror, Mystery",572 min,8.6\nRate

Q--8--> Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You
have to find the following details:
    
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year

 Note: - from the home page you have to go to the Show All Dataset page through code.

In [14]:
driver=webdriver.Chrome()
driver.get('https://archive.ics.uci.edu/')

driver.find_element(By.CLASS_NAME,'btn-primary').click()

In [89]:
name=[]
types=[]
task=[]
attribute=[]
instances=[]
no_attribute=[]
year=[]

# for Dataset name
na=driver.find_elements(By.CLASS_NAME,'font-semibold') 
for i in na:
    name.append(i.text)
    
name.pop(0),name.pop(0),name.pop()


# for Data Types
types=[]
typ=driver.find_elements(By.CLASS_NAME,'col-span-3')
for i in typ:
    types.append(i.text)
    types=types[0:10]
    
    
# for attribute
att=driver.find_elements(By.CLASS_NAME,'col-span-3')
for i in att:
    attribute.append(i.text)
    attribute=attribute[0:10]

In [90]:
# for task
# By Beautiful soup
import bs4
from bs4 import BeautifulSoup
import requests
url='https://archive.ics.uci.edu/datasets?search'
page=requests.get(url)

soup=BeautifulSoup(page.content)

task=[]
ta=soup.find_all('span',class_="truncate")
for i in ta:
    task.append(i.text)
    task=task[0:10]

In [91]:
print(len(name),len(types),len(task),len(attribute),len(instances),len(no_attribute),len(year))

10 10 10 10 0 0 0

In [92]:
# for Data Frame
df=pd.DataFrame({'Name':name,'type':types ,'Task':task,'Attribute':attribute})
df

,Name,type,Task,Attribute
0,Iris,Classification,Classification,Classification
1,Heart Disease,Tabular,Tabular,Tabular
2,Adult,150 Instances,150 Instances,150 Instances
3,Wine,4 Features,4 Features,4 Features
4,Breast Cancer Wisconsin (Diagnostic),Classification,Classification,Classification
5,Diabetes,Multivariate,Multivariate,Multivariate
6,Dry Bean Dataset,303 Instances,303 Instances,303 Instances
7,Car Evaluation,13 Features,13 Features,13 Features
8,Wine Quality,Classification,Classification,Classification
9,Bank Marketing,Multivariate,Multivariate,Multivariate